name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dockerbuild
      run: docker build . --file Dockerfile --tag ${{secrets.USERNAME}}/python-docker:latest
    - name: docker login
      run: docker login --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}}
    - name: dockerpush
      run: docker push ${{secrets.USERNAME}}/python-docker:latest
